export const BridgeTemplate = [
    {"name":"site_clearance", "qty":"", "amount":"", "unit":""},
    {"name":"clearance_of_trees_building", "qty":"", "amount":"", "unit":""},
    {"name":"scarify_shape_and_compact", "qty":"", "amount":"", "unit":""},
    {"name":"escavation_for_culverts", "qty":"", "amount":"", "unit":""},
    {"name":"grassing_stone_pitching_ripraps", "qty":"", "amount":"", "unit":""},
    {"name":"diameter_pipe", "qty":"", "amount":"", "unit":""},
    {"name":"concrete_grade_retaining_wall", "qty":"", "amount":"", "unit":""},
    {"name":"reinforcement_to_culvert_retaining_wall", "qty":"", "amount":"", "unit":""},
    {"name":"concrete_line_drains", "qty":"", "amount":"", "unit":""},
    {"name":"miscellanous_culvert_works", "qty":"", "amount":"", "unit":""},
    {"name":"latentic_sub_base", "qty":"", "amount":"", "unit":""},
    {"name":"stonebase", "qty":"", "amount":"", "unit":""},
    {"name":"prime_coat", "qty":"", "amount":"", "unit":""},
    {"name":"binder_course", "qty":"", "amount":"", "unit":""},
    {"name":"tack_coat", "qty":"", "amount":"", "unit":""},
    {"name":"wearing_course", "qty":"", "amount":"", "unit":""},
    {"name":"surface_dressing", "qty":"", "amount":"", "unit":""},
    {"name":"km_posts_kerbs_rails_and_crash_barriers", "qty":"", "amount":"", "unit":""},
    {"name":"escavation_piling", "qty":"", "amount":"", "unit":""},
    {"name":"abutment_piers_and_pile_caps", "qty":"", "amount":"", "unit":""},
    {"name":"concrete_km_post", "qty":"", "amount":"", "unit":""},
    {"name":"escavation", "qty":"", "amount":"", "unit":""},
    {"name":"concrete_box_girder_superstructure", "qty":"", "amount":"", "unit":""},
    {"name":"bearing_number", "qty":"", "amount":"", "unit":""},
    {"name":"reinforcement", "qty":"", "amount":"", "unit":""},
    {"name":"expansion_joints", "qty":"", "amount":"", "unit":""},
    {"name":"cast_iron_drains", "qty":"", "amount":"", "unit":""}
 
]